### ISSUE TITLE
Add databinding support?

### ISSUE THREAD

**Issue by Fuhrmann** [abdularis/CircularImageView#1]
Hey, thanks for your work.

I'm using your library together with google library for databinding. This is my code:

```
<com.github.abdularis.civ.AvatarImageView
            android:layout_width="@dimen/material_list_avatar_size"
            android:layout_height="@dimen/material_list_avatar_size"
            app:avatar_backgroundColor="@color/colorPrimaryDark"
            app:avatar_text="@{item.firstLetterName())}"
            app:avatar_textSize="22sp"
            app:strokeColor="@android:color/black"
            app:strokeWidth="1dp" />
```

This is the error I get after trying to build:

```
[kapt] An exception occurred: android.databinding.tool.util.LoggedErrorException: Found data binding errors.
****/ data binding error ****msg:Cannot find the setter for attribute 'app:avatar_text' with parameter type java.lang.String on com.github.abdularis.civ.AvatarImageView.
```

To solve this issue, I had to explicity declare a binding adapter:

```
class BindingAdapterUtils {

    companion object {
        @JvmStatic
        @BindingAdapter("app:avatar_text")
        fun setAvatarText(view: AvatarImageView, text: String) {
            view.initial = text
        }
    }
}
```

After that everything works fine. It may be possible to include native support for databinding? So others users dont get the same error.

**Comment by abdularis** [comment]
Actually i'm not using data binding so I didn't notice that.
to make data binding works out of the box, I think we have to change the API of _AvatarImageView_ (like setter & getter) to match xml attributes, instead of enabling data binding (introducing new dependency) or defining adapter in the library.

so it might be incompatible with the previous version.

[https://github.com/abdularis/CircularImageView/tree/v2](https://github.com/abdularis/CircularImageView/tree/v2)

~~~xml
<declare-styleable name="AvatarImageView">
        <attr name="avatarBackgroundColor" format="color"/>
        <attr name="initialSize" format="dimension"/>
        <attr name="initialColor" format="color"/>
        <attr name="initial" format="string"/>
        <attr name="state" format="enum">
            <enum name="INITIAL" value="1"/>
            <enum name="IMAGE" value="2"/>
        </attr>
    </declare-styleable>
~~~
which one is more explicit/clear, is it 'initial' or 'firstLetter'

**Comment by Fuhrmann** [comment]
Ok! Actually this is just a minor enhancement, since I got working just by setting up an custom BindingAdapter. But, I think `initial` would be better, because you're already using `initialSize`, `initialColor`, so keeping the same name pattern is good.

I'll try the new version, thanks!

**Comment by abdularis** [comment]
Ok, we'll stick with v1.2
